### ISSUE TITLE
Jellyfin Support

### ISSUE THREAD

**Issue by FiveMDevv** [rivenmedia/riven#465] opened 2024-06-24 05:20 UTC

**Comment by AyushSehrawat** [comment] 2024-06-24 13:26
Currently there is a local_mode in settings which just makes the symlink. You could try to use it with jellyfish and manually scan. Isn't tested but who knows, might work :)

**Comment by dreulavelle** [comment] 2024-06-30 14:27
All I need to add JF is how to handle dir refreshing.. all I could see from the jellyfin api was that it would refresh all of JF entirely.. which isn't what I wanna do :P

**Comment by AyushSehrawat** [comment] 2024-06-30 14:29
> All I need to add JF is how to handle dir refreshing.. all I could see from the jellyfin api was that it would refresh all of JF entirely.. which isn't what I wanna do :P

There's partial too iirc

**Comment by dreulavelle** [comment] 2024-06-30 14:29
I didn't see it in their api, but if there is that would be awesome

**Comment by DrMxrcy** [comment] 2024-06-30 15:17
I took a look on how autoscan works with jellyfin.

It looks like you should be able to use the endpoint Library/Media/Updated to tell jellyfin they have new media. 
https://api.jellyfin.org/#tag/Library/operation/PostUpdatedMedia

**Comment by dreulavelle** [comment] 2024-06-30 15:21
![image](https://github.com/rivenmedia/riven/assets/5782630/b4f0e986-b257-44b8-9705-ac77f4bacfa4)

Beautiful! Nice work @DrMxrcy :)

**Comment by ZombieApps** [comment] 2024-07-01 05:42
I can confirm the same API works with Emby.  I've been using it for manual folder updates.

**Comment by dreulavelle** [comment] 2024-07-01 05:48
> I can confirm the same API works with Emby. I've been using it for manual folder updates.

Can you give me a couple examples by chance what it looks like? Thats awesome that it works for both.. so I should be able to duplicate the JF updater into Emby.. 2 for 1 :D

**Comment by DrMxrcy** [comment] 2024-07-01 05:54
Since JF is based off of Emby, seems like the API Is similar. Going back to my autoscan example, they are calling Emby related functions in the JF API https://github.com/saltydk/autoscan/blob/1525966c3e1ca301fce9b9ee0460ccba2d0b7c39/targets/jellyfin/api.go#L31

**Comment by DrMxrcy** [comment] 2024-07-01 05:55
https://swagger.emby.media/?staticview=true#/LibraryService/postLibraryMediaUpdated

![image](https://github.com/rivenmedia/riven/assets/58747968/0ab8e171-c0c1-43a6-b570-ef072531cc47)

**Comment by ZombieApps** [comment] 2024-07-01 06:10
> > I can confirm the same API works with Emby. I've been using it for manual folder updates.
> 
> Can you give me a couple examples by chance what it looks like? Thats awesome that it works for both.. so I should be able to duplicate the JF updater into Emby.. 2 for 1 :D

Please excuse the Perl.. It's the language I'm most comfortable in for quick & dirty scripts :grinning: 

I had to create a separate user on Emby because the regular API key doesn't have permission to make library changes.

But the basic idea is you authenticate with ` http://$hostname:8096/emby/Users/AuthenticateByName`, which gives an `AccessToken`
You can reuse that token until it expires, so I only reauth if needed
Pass that token through with the `X-Emby-Token:` header and post the following json to `http://$hostname:8096/emby/Library/Media/Updated`

```json

    { 
       "Updates": 
       [ 
          {  
             "Path": "$dir",
             "UpdateType": "Modified"
          }
        ] 
    } 

```

where UpdateType can be Created/Modified/Deleted.

```perl

#!/usr/bin/perl
  
if (! defined $ARGV[0] or ! -e "$ARGV[0]") {
  print "Please specify a directory name in /media/symlinks\n";
  exit;
}   
    
$dir=shift;
    
use JSON;
use WWW::Curl::Easy;
    
$emby = "http://localhost:8096/emby";
    
$user = "Perl";
$pass="REDACTED";


$client="X-Emby-Client=Perl&X-Emby-Device-Name=Perl&X-Emby-Device-Id=ffffffff-ffff-ffff-ffff-ffffffffffff&X-Emby-Client-Version=5.36.0";

my $curl = WWW::Curl::Easy->new;
$curl->setopt(CURLOPT_HEADER,0);
$curl->setopt(CURLOPT_CONNECTTIMEOUT,30);
$curl->pushopt(CURLOPT_HTTPHEADER,["Content-Type: application/json"]);
##########################################################################

open (TOKENFILE, "/opt/EmbyAPI/auth/token.txt");
$accesstoken=<TOKENFILE>;
close (TOKENFILE);
chomp $accesstoken;

# check to see if we need to get a new token
my $statusurl="$emby/System/Info";

$curl->setopt(CURLOPT_URL, $statusurl);
$curl->pushopt(CURLOPT_HTTPHEADER,["X-Emby-Token: $accesstoken"]);
$curl->setopt(CURLOPT_POST, 0);
my $poll_body;
$curl->setopt(CURLOPT_WRITEDATA,\$poll_body);
my $curlresponse = $curl->perform;
my $http_response = $curl->getinfo(CURLINFO_RESPONSE_CODE);
if ($curlresponse == 0 and $http_response == 200) {
  print "already authenticated\n";
} elsif ($http_response == 401) {
  print "need to reauthenticate\n";
  my $loginurl="$emby/Users/AuthenticateByName?$client";

  my $loginjson="
  {
  \"Username\": \"Perl\",
  \"Pw\": \"VMQe~w]3%Pg{Jli\"
  }";
  
  
  # log into emby

  $curl->setopt(CURLOPT_URL, $loginurl);
  $curl->setopt(CURLOPT_POST, 1);
  $curl->setopt(CURLOPT_POSTFIELDS(), $loginjson);

  my $poll_body;
  $curl->setopt(CURLOPT_WRITEDATA,\$poll_body);
  my $curlresponse = $curl->perform;
  my $http_response = $curl->getinfo(CURLINFO_RESPONSE_CODE);
  if ($curlresponse == 0 and $http_response == 200) {
    my $json = decode_json( $poll_body );
    $accesstoken = $json->{"AccessToken"};
    #print "logged in with access token $accesstoken\n";
    $curl->pushopt(CURLOPT_HTTPHEADER,["X-Emby-Token: $accesstoken"]);
    open (TOKENFILE, ">/opt/EmbyAPI/auth/token.txt");
    print TOKENFILE "$accesstoken\n";
    close (TOKENFILE);
  } else {
    print "login failed with response: $curlresponse / $http_response\n";
    exit;
  }
} else {
  print "unknown status $http_response, curl status $curlresponse\n";
}

####################################
$updateurl="$emby/Library/Media/Updated";

$updatejson="
    { 
       \"Updates\": 
       [ 
          {  
             \"Path\": \"$dir\",                              
             \"UpdateType\": \"Modified\"                     
          }
        ] 
    }";


$curl->setopt(CURLOPT_URL, $updateurl);
$curl->setopt(CURLOPT_POST, 1);
$curl->setopt(CURLOPT_POSTFIELDS(), $updatejson);
my $curlresponse = $curl->perform;
my $http_response = $curl->getinfo(CURLINFO_RESPONSE_CODE);
if ($curlresponse == 0 and $http_response == 204) {
  print "$dir update sent\n";


```

**Comment by ZombieApps** [comment] 2024-07-01 06:19
The other thing that trips Riven up is that Emby (and I believe Jellyfin) likes to put theme music and posters in the main directory for each show/movie and for shows that gets Riven all confused and crashes when it starts with a blank database - and then won't re-scan the rest of the folders when I restart it.
I work around that by temporarily removing `shows/*/*.mp3` and `shows/*/*.jpg` before starting Riven with a clean slate.

```
24-07-01 13:38:17 | ❌ ERROR     | main.<module> - Error in main thread: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (2018) {imdb-tt7678620}/theme.mp3'
24-07-01 13:38:17 | ❌ ERROR     | main.<module> - Traceback (most recent call last):
  File "/riven/backend/main.py", line 112, in <module>     app.program.start()
  File "/riven/backend/program/program.py", line 154, in start     for item in self.services[SymlinkLibrary].run():
  File "/riven/backend/program/libraries/symlink.py", line 51, in run     yield from process_shows(self.settings.library_path / directory, item_type, is_anime)
  File "/riven/backend/program/libraries/symlink.py", line 96, in process_shows
    for episode in os.listdir(directory / show / season):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (2018) {imdb-tt7678620}/theme.mp3'

Traceback (most recent call last):

  File "/riven/backend/main.py", line 112, in <module>
    app.program.start()
    │   │       └ <function Program.start at 0x7f676667cae0>
    │   └ <Program(Riven, initial)>
    └ <fastapi.applications.FastAPI object at 0x7f6766694cd0>

  File "/riven/backend/program/program.py", line 154, in start
    for item in self.services[SymlinkLibrary].run():
        │       │    │        └ <class 'program.libraries.symlink.SymlinkLibrary
'>
        │       │    └ {<class 'program.libraries.symlink.SymlinkLibrary'>: <pro
gram.libraries.symlink.SymlinkLibrary object at 0x7f6766963c90>, <cl...
        │       └ <Program(Riven, initial)>
        └ Show:Don't Hug Me I'm Scared:Completed

  File "/riven/backend/program/libraries/symlink.py", line 51, in run
    yield from process_shows(self.settings.library_path / directory, item_type, 
is_anime)
               │             │    │        │              │          │          
└ False
               │             │    │        │              │          └ 'show'
               │             │    │        │              └ 'shows'
               │             │    │        └ PosixPath('/media/symlinks')
               │             │    └ SymlinkModel(rclone_path=PosixPath('/data/pd_zurg/__all__'), library_path=PosixPath('/media/symlinks'), separate_anime_dirs=
F...
               │             └ <program.libraries.symlink.SymlinkLibrary object 
at 0x7f6766963c90>
               └ <function process_shows at 0x7f6766b78400>

  File "/riven/backend/program/libraries/symlink.py", line 96, in process_shows
    for episode in os.listdir(directory / show / season):
        │          │  │       │           │      └ 'theme.mp3'
        │          │  │       │           └ 'Bluey (2018) {imdb-tt7678620}'
        │          │  │       └ PosixPath('/media/symlinks/shows')
        │          │  └ <built-in function listdir>
        │          └ <module 'os' (frozen)>
        └ "Don't Hug Me I'm Scared (2022) - s01e01 - Jobs.mkv"

NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (20
18) {imdb-tt7678620}/theme.mp3'
24-07-01 13:38:17 |  CRITICAL  | main.<module> - Server has been stopped
```

**Comment by AyushSehrawat** [comment] 2024-07-01 06:27
> But the basic idea is you authenticate with  http://$hostname:8096/emby/Users/AuthenticateByName, which gives an AccessToken
You can reuse that token until it expires, so I only reauth if needed

Ig this can be added in frontend like plex oauth. 


> You can reuse that token until it expires, so I only reauth if needed

How long is the token valid ?

> I work around that by temporarily removing shows/*/*.mp3 and shows/*/*.jpg before starting Riven with a clean slate.

I only played with jellyfin for a but but it didn't make mp3 files or jpg files for me, maybe i disabled them ?

**Comment by AyushSehrawat** [comment] 2024-07-01 06:28
> NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (2018) {imdb-tt7678620}/theme.mp3'

Another way can be to ignore extensions in code when looping 🤔

**Comment by dreulavelle** [comment] 2024-07-01 06:30
Since we're forcing it to update a specific path, we shouldn't have this issue?

> The other thing that trips Riven up is that Emby (and I believe Jellyfin) likes to put theme music and posters in the main directory for each show/movie and for shows that gets Riven all confused and crashes when it starts with a blank database - and then won't re-scan the rest of the folders when I restart it. I work around that by temporarily removing `shows/*/*.mp3` and `shows/*/*.jpg` before starting Riven with a clean slate.
> 
> ```
> 24-07-01 13:38:17 | ❌ ERROR     | main.<module> - Error in main thread: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (2018) {imdb-tt7678620}/theme.mp3'
> 24-07-01 13:38:17 | ❌ ERROR     | main.<module> - Traceback (most recent call last):
>   File "/riven/backend/main.py", line 112, in <module>     app.program.start()
>   File "/riven/backend/program/program.py", line 154, in start     for item in self.services[SymlinkLibrary].run():
>   File "/riven/backend/program/libraries/symlink.py", line 51, in run     yield from process_shows(self.settings.library_path / directory, item_type, is_anime)
>   File "/riven/backend/program/libraries/symlink.py", line 96, in process_shows
>     for episode in os.listdir(directory / show / season):
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (2018) {imdb-tt7678620}/theme.mp3'
> 
> Traceback (most recent call last):
> 
>   File "/riven/backend/main.py", line 112, in <module>
>     app.program.start()
>     │   │       └ <function Program.start at 0x7f676667cae0>
>     │   └ <Program(Riven, initial)>
>     └ <fastapi.applications.FastAPI object at 0x7f6766694cd0>
> 
>   File "/riven/backend/program/program.py", line 154, in start
>     for item in self.services[SymlinkLibrary].run():
>         │       │    │        └ <class 'program.libraries.symlink.SymlinkLibrary
> '>
>         │       │    └ {<class 'program.libraries.symlink.SymlinkLibrary'>: <pro
> gram.libraries.symlink.SymlinkLibrary object at 0x7f6766963c90>, <cl...
>         │       └ <Program(Riven, initial)>
>         └ Show:Don't Hug Me I'm Scared:Completed
> 
>   File "/riven/backend/program/libraries/symlink.py", line 51, in run
>     yield from process_shows(self.settings.library_path / directory, item_type, 
> is_anime)
>                │             │    │        │              │          │          
> └ False
>                │             │    │        │              │          └ 'show'
>                │             │    │        │              └ 'shows'
>                │             │    │        └ PosixPath('/media/symlinks')
>                │             │    └ SymlinkModel(rclone_path=PosixPath('/data/pd_zurg/__all__'), library_path=PosixPath('/media/symlinks'), separate_anime_dirs=
> F...
>                │             └ <program.libraries.symlink.SymlinkLibrary object 
> at 0x7f6766963c90>
>                └ <function process_shows at 0x7f6766b78400>
> 
>   File "/riven/backend/program/libraries/symlink.py", line 96, in process_shows
>     for episode in os.listdir(directory / show / season):
>         │          │  │       │           │      └ 'theme.mp3'
>         │          │  │       │           └ 'Bluey (2018) {imdb-tt7678620}'
>         │          │  │       └ PosixPath('/media/symlinks/shows')
>         │          │  └ <built-in function listdir>
>         │          └ <module 'os' (frozen)>
>         └ "Don't Hug Me I'm Scared (2022) - s01e01 - Jobs.mkv"
> 
> NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (20
> 18) {imdb-tt7678620}/theme.mp3'
> 24-07-01 13:38:17 |  CRITICAL  | main.<module> - Server has been stopped
> ```

**Comment by AyushSehrawat** [comment] 2024-07-01 06:32
> Since we're forcing it to update a specific path, we shouldn't have this issue?

I think it's checking symlink for missing seasons or episodes

**Comment by dreulavelle** [comment] 2024-07-01 06:34
> File "/riven/backend/program/libraries/symlink.py", line 96, in process_shows
>     for episode in os.listdir(directory / show / season):
>         │          │  │       │           │      └ 'theme.mp3'
>         │          │  │       │           └ 'Bluey (2018) {imdb-tt7678620}'
>         │          │  │       └ PosixPath('/media/symlinks/shows')
>         │          │  └ <built-in function listdir>
>         │          └ <module 'os' (frozen)>
>         └ "Don't Hug Me I'm Scared (2022) - s01e01 - Jobs.mkv"
> 
> NotADirectoryError: [Errno 20] Not a directory: '/media/symlinks/shows/Bluey (20
> 18) {imdb-tt7678620}/theme.mp3'
> 24-07-01 13:38:17 |  CRITICAL  | main.<module> - Server has been stopped

wtf lol.. what did you do 😂

**Comment by ZombieApps** [comment] 2024-07-01 06:34
> Since we're forcing it to update a specific path, we shouldn't have this issue?
> 
> >

The mp3/jpg errors are only on Riven's first startup with no  media.pkl or  media.pkl.bak and it's mapping existing symlink folders.  It's not related to the update script, just thought I should mention it because it'll trip up other new Riven users.

**Comment by ZombieApps** [comment] 2024-07-01 06:38
> wtf lol.. what did you do 😂

:man_shrugging: 

This is what Emby does to the directory structure if you've got the various "Theme Songs" and "Theme Videos" plugins enabled - and the user can have those playing while they're browsing, just like Plex.

idiotbox /media/symlinks/series # ls Bluey\ \(2018\)\ \{imdb-tt7678620\}/
backdrops/     landscape.jpg  season01-poster.jpg  Season 03/
clearlogo.png  poster.jpg     Season 02/           season03-poster.jpg
fanart.jpg     Season 01/     season02-poster.jpg  theme.mp3

**Comment by davidemarcoli** [comment] 2024-07-08 13:30
Riven should just ignore it if it's not a folder.

**Comment by dreulavelle** [comment] 2024-07-13 01:46
Closing as this is already slated to be supported soon! :)

**Closed by dreulavelle** 2024-07-13 01:46 UTC
Labels: enhancement, backend
